version: '3'
services:
    db:
        build: 
            context: ./src/db
        environment: 
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            GEOCODER_STATES: "${GEOCODER_STATES}"
            GEOCODER_YEAR: "${GEOCODER_YEAR}"
        ports:
            - "5432:5432"
        networks:
            default:
                aliases:
                    - db
        shm_size: 1g
        volumes:
            - ./volumes/gisdata:/gisdata
            - ./volumes/var2/lib/postgresql/data:/var/lib/postgresql/data
    api:
        build:
            context: ./src/server
        environment: 
            POSTGRES_HOST: db
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        ports:
            - "5000:5000"
        depends_on:
            - db
        networks:
            default:
                aliases:
                    - api

networks:
    default:
        driver: bridge